apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: food-delivery
data:
  PORT: "4000"
  FRONTEND_URL: "https://food.trungdevops.vn"
  CORS_ORIGINS: "https://food.trungdevops.vn,https://admin.food.trungdevops.vn"
