apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: food-delivery
data:
  PORT: "4000"
  FRONTEND_URL: "http://food.trungdevops.vn"
  CORS_ORIGINS: "http://food.trungdevops.vn,http://admin.food.trungdevops.vn"
