apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace.name }}
  labels:
    app: backend
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          {{- if .Values.backend.persistence.enabled }}
          volumeMounts:
            - name: uploads
              mountPath: {{ .Values.backend.persistence.mountPath }}
          {{- end }}
      {{- if .Values.backend.persistence.enabled }}
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: backend-uploads-pvc
      {{- end }}
